name:               "Toshiyuki Hirakata"
description:        "portfolio of toshiyuki hirakata"

url:                ""
author:             "Toshiyuki Hirakata"
email:              "hirakata@kde.cs.tsukuba.ac.jp"
gravatar_hash:      ""
twitter:            ""
email:              "hirakata@kde.cs.tsukuba.ac.jp"
github:             "hiratekatayama"
pinterest:          ""
linkedin:           ""
facebook:           ""

disqus_shortname:   "thinker3197"

#background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

#paginate:           5
#paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About Me"
    href:           "#aboutme"
  - name:           "Research Interest"
    href:           "#research"
  - name:           "Publications"
    href:           "#publications"
  - name:           "Awards"
    href:           "#awards"
  - name:           "Personal Interest"
    href:           "#personal"
  - name:           "Experience"
    href:           "#experience"
  - name:           "Education"
    href:           "#education"
  - name:           "License"
    href:           "#licenses"
  - name:           "Competition・Hackathon"
    href:           "#competitionhackathon"
  - name:           "Club Activity"
    href:           "#club"
  - name:           "Hobby"
    href:           "#hobby"

sass:
  style:            :compressed
